---
apiVersion: iam/v2
kind: Group
metadata:
  name: payments-owners
spec:
  displayName: Payments
  description: Group for the Payments owners
  externalGroups:
    - payments-owners
---
apiVersion: iam/v2
kind: Group
metadata:
  name: payments-devs
spec:
  displayName: Payments
  description: Group for the Payments developers
  externalGroups:
    - payments-devs
