apiVersion: self-serve/v1
kind: ApplicationGroup
metadata:
  application: payments
  name: payments-dev-ui-permissions
spec:
  displayName: "Payments Developers"
  description: "Payments developrs get full access to payments resources in dev environment"
  members: [] # Use externalGroups for IdP-managed membership
  externalGroups:
    - payments-devs
  permissions:
    - appInstance: payments-dev
      resourceType: TOPIC
      patternType: LITERAL
      name: "*" # wildcard '*' is of course scoped to what this application instance owns
      permissions:
        - topicViewConfig
        - topicConsume
        - topicProduce
        - topicEditConfig
        - topicCreate
        - topicDelete
