apiVersion: kafka/v2
kind: Topic
metadata:
  cluster: "kafka-dev" # Must match the ApplicationInstance cluster
  name: payments.transactions
  labels:
    instance: dev
    business-unit: finance
    confidentiality: restricted
    team: payments-team
spec:
  replicationFactor: 3
  partitions: 3
  configs:
    cleanup.policy: delete
    retention.ms: "86400000" # 1 day
