apiVersion: self-serve/v1
kind: ResourcePolicy
metadata:
  name: topic-rules-dev
spec:
  targetKind: Topic
  description: "Relaxed topic rules for dev environments"
  rules:
    - condition: spec.replicationFactor >= 1
      errorMessage: "Replication factor has to be at least 1"
    - condition: spec.partitions >= 1 && spec.partitions <= 3
      errorMessage: "Partition count has to be between 1 and 3"
